### ISSUE TITLE
assertSchemaPut for single updates

### ISSUE THREAD

**Issue by tmacjx** [yeti/YAK-server#30]
I recently user assertSchemaPut for an put action on single entry.
For example: I want to update an user's profile

Put  /user/1/

data = {
    "name": "user1",
    "city": "NY"
}

response = self.assertSchemaPut(url, request_object_name, response_object_name, data, user=self.admin).
And the console show some error:

    self.check_schema_keys(data[0], self.schema_objects[request_object_name])
   KeyError: 0

I guess the method not support for single update.But if there any way work for me to update single entry?

**Comment by tmacjx** [comment]
def assertSchemaPut(
            self,
            url,
            request_object_name,
            response_object_name,
            data,
            user,
            format="json",
            unauthorized=False,
            forbidden=False):
        """
        Assumes PUT is used for bulk updates, not single updates.
        Runs a PUT request and checks the PUT data and results match the
        schema for bulk updates. Assumes that all objects sent in a bulk
        update are identical, and hence only checks that the first one
        matches the schema.
        """

**Comment by baylee** [comment]
@tmacjx you can use PATCH and `assertSchemaPatch` for updates of single objects

**Comment by tmacjx** [comment]
@baylee  thanks a lot
